// Os registros do Uni+: cada mutirão é a "Oferta" do KiOferta.
// O número que decide (o "Preço") é quantos voluntários ainda faltam:
//   vagasTotal - vagasPreenchidas.
// O segundo critério (a "Distância") é a data: quantos dias faltam.
//
// As datas são calculadas a partir de hoje, para que a demonstração
// nunca mostre mutirões vencidos, não importa o dia em que o app rodar.

function daquiA(dias) {
  const data = new Date()
  data.setDate(data.getDate() + dias)
  const ano = data.getFullYear()
  const mes = String(data.getMonth() + 1).padStart(2, '0')
  const dia = String(data.getDate()).padStart(2, '0')
  return `${ano}-${mes}-${dia}`
}

const mutiroes = [
  {
    id: 1,
    titulo: 'Sopa solidária de sábado',
    categoria: 'Alimentação',
    organizacaoId: 1,
    publicadoPor: 1,
    data: daquiA(3),
    horaInicio: '08:00',
    horaFim: '13:00',
    local: 'Cozinha do Instituto SOPA',
    bairro: 'Vila Industrial',
    vagasTotal: 15,
    vagasPreenchidas: 6,
    precisa: ['Descascar legumes', 'Servir as mesas', 'Lavar panelas'],
    requisitos: 'A partir de 16 anos. Cabelo preso e sapato fechado.',
    descricao: 'Preparo e distribuição da sopa para as famílias atendidas no fim de semana.',
  },
  {
    id: 2,
    titulo: 'Montagem de cestas básicas',
    categoria: 'Alimentação',
    organizacaoId: 1,
    publicadoPor: 1,
    data: daquiA(10),
    horaInicio: '14:00',
    horaFim: '18:00',
    local: 'Galpão do Instituto SOPA',
    bairro: 'Vila Industrial',
    vagasTotal: 20,
    vagasPreenchidas: 17,
    precisa: ['Separar alimentos', 'Montar caixas', 'Carregar a van'],
    requisitos: 'Nenhum. Quem puder levantar peso, avise no dia.',
    descricao: 'Separação dos alimentos doados e montagem das cestas do mês.',
  },
  {
    id: 3,
    titulo: 'Campanha Pé Quentinho: triagem de meias e cobertores',
    categoria: 'Arrecadação',
    organizacaoId: 2,
    publicadoPor: 2,
    data: daquiA(5),
    horaInicio: '09:00',
    horaFim: '12:00',
    local: 'Sede da Associação do Voluntariado',
    bairro: 'Centro',
    vagasTotal: 12,
    vagasPreenchidas: 3,
    precisa: ['Separar por tamanho', 'Conferir estado das peças', 'Embalar kits'],
    requisitos: 'Nenhum.',
    descricao: 'Triagem do que chegou na campanha antes da entrega para as instituições parceiras.',
  },
  {
    id: 4,
    titulo: 'Ponto de coleta na praça',
    categoria: 'Arrecadação',
    organizacaoId: 2,
    publicadoPor: 2,
    data: daquiA(12),
    horaInicio: '10:00',
    horaFim: '16:00',
    local: 'Praça Oswaldo Cruz',
    bairro: 'Centro',
    vagasTotal: 8,
    vagasPreenchidas: 2,
    precisa: ['Receber doações', 'Explicar a campanha', 'Montar a tenda'],
    requisitos: 'Gostar de conversar com quem passa.',
    descricao: 'Barraca de arrecadação de agasalhos e alimentos não perecíveis.',
  },
  {
    id: 5,
    titulo: 'Leitura nos quartos da pediatria',
    categoria: 'Saúde',
    organizacaoId: 3,
    publicadoPor: 3,
    data: daquiA(4),
    horaInicio: '14:00',
    horaFim: '18:00',
    local: 'Santa Casa de Mogi das Cruzes',
    bairro: 'Centro',
    vagasTotal: 6,
    vagasPreenchidas: 6,
    precisa: ['Ler histórias', 'Acompanhar as crianças na brinquedoteca'],
    requisitos: 'Maiores de 18 anos e disponibilidade de 4 horas semanais.',
    descricao: 'Momento de leitura com as crianças internadas, junto com a equipe da AVOSC.',
  },
  {
    id: 6,
    titulo: 'Acolhimento de acompanhantes',
    categoria: 'Saúde',
    organizacaoId: 3,
    publicadoPor: 3,
    data: daquiA(15),
    horaInicio: '07:00',
    horaFim: '11:00',
    local: 'Santa Casa de Mogi das Cruzes',
    bairro: 'Centro',
    vagasTotal: 10,
    vagasPreenchidas: 1,
    precisa: ['Orientar acompanhantes', 'Servir café da manhã'],
    requisitos: 'Maiores de 18 anos e disponibilidade de 4 horas semanais.',
    descricao: 'Recepção de familiares que passam a noite no hospital.',
  },
  {
    id: 7,
    titulo: 'Oficina de pipas com as crianças',
    categoria: 'Crianças',
    organizacaoId: 4,
    publicadoPor: 4,
    data: daquiA(6),
    horaInicio: '13:30',
    horaFim: '17:00',
    local: 'Centro Comunitário José de Paiva Netto',
    bairro: 'Porteira Preta',
    vagasTotal: 8,
    vagasPreenchidas: 5,
    precisa: ['Ajudar a montar pipas', 'Organizar a fila', 'Lanche da tarde'],
    requisitos: 'Maiores de 18 anos.',
    descricao: 'Oficina ao ar livre com as turmas do atendimento socioeducativo.',
  },
  {
    id: 8,
    titulo: 'Pintura das salas do centro comunitário',
    categoria: 'Reforma e limpeza',
    organizacaoId: 4,
    publicadoPor: 4,
    data: daquiA(20),
    horaInicio: '08:00',
    horaFim: '16:00',
    local: 'Centro Comunitário José de Paiva Netto',
    bairro: 'Porteira Preta',
    vagasTotal: 25,
    vagasPreenchidas: 9,
    precisa: ['Lixar paredes', 'Pintar', 'Rolos e pincéis'],
    requisitos: 'Roupa que possa sujar. Almoço por conta da organização.',
    descricao: 'Mutirão para renovar três salas antes das férias.',
  },
  {
    id: 9,
    titulo: 'Reforço escolar de matemática',
    categoria: 'Crianças',
    organizacaoId: 5,
    publicadoPor: 5,
    data: daquiA(7),
    horaInicio: '14:00',
    horaFim: '16:00',
    local: 'Sede da ABRAC (endereço pelo contato)',
    bairro: 'Mogi das Cruzes',
    vagasTotal: 5,
    vagasPreenchidas: 2,
    precisa: ['Explicar exercícios', 'Material escolar'],
    requisitos: 'Maiores de 18 anos. Ensino médio completo.',
    descricao: 'Apoio nas tarefas de casa de crianças do 5º ao 9º ano.',
  },
  {
    id: 10,
    titulo: 'Arrecadação de produtos de limpeza',
    categoria: 'Arrecadação',
    organizacaoId: 5,
    publicadoPor: 5,
    data: daquiA(8),
    horaInicio: '09:00',
    horaFim: '13:00',
    local: 'Sede da ABRAC (endereço pelo contato)',
    bairro: 'Mogi das Cruzes',
    vagasTotal: 6,
    vagasPreenchidas: 0,
    precisa: ['Receber doações', 'Separar por tipo', 'Detergente e sabão em pó'],
    requisitos: 'Nenhum.',
    descricao: 'Dia de recebimento de gêneros alimentícios e produtos de limpeza.',
  },
  {
    id: 11,
    titulo: 'Entrega de ração para protetores',
    categoria: 'Animais',
    organizacaoId: 6,
    publicadoPor: 6,
    data: daquiA(2),
    horaInicio: '09:00',
    horaFim: '12:00',
    local: 'Ponto de encontro no terminal',
    bairro: 'Jundiapeba',
    vagasTotal: 10,
    vagasPreenchidas: 7,
    precisa: ['Carro para entregas', 'Separar sacos de ração'],
    requisitos: 'Para a entrega, motorista habilitado.',
    descricao: 'Distribuição de ração doada para protetores independentes do bairro.',
  },
  {
    id: 12,
    titulo: 'Rota noturna de marmitas e kits de higiene',
    categoria: 'Alimentação',
    organizacaoId: 6,
    publicadoPor: 6,
    data: daquiA(9),
    horaInicio: '19:00',
    horaFim: '22:00',
    local: 'Saída da Praça Coronel Almeida',
    bairro: 'Centro',
    vagasTotal: 14,
    vagasPreenchidas: 4,
    precisa: ['Entregar marmitas', 'Montar kits de higiene', 'Cobertores'],
    requisitos: 'Maiores de 18 anos.',
    descricao: 'Distribuição de refeição e kits para pessoas em situação de rua.',
  },
  {
    id: 13,
    titulo: 'Limpeza e plantio na praça do bairro',
    categoria: 'Reforma e limpeza',
    organizacaoId: 2,
    publicadoPor: 2,
    data: daquiA(16),
    horaInicio: '08:00',
    horaFim: '12:00',
    local: 'Praça central do bairro',
    bairro: 'Jardim Universo',
    vagasTotal: 30,
    vagasPreenchidas: 11,
    precisa: ['Recolher lixo', 'Plantar mudas', 'Luvas e sacos'],
    requisitos: 'Nenhum. Crianças acompanhadas são bem-vindas.',
    descricao: 'Mutirão com os moradores para limpar a praça e plantar mudas nativas.',
  },
  {
    id: 14,
    titulo: 'Bazar beneficente: organização das peças',
    categoria: 'Arrecadação',
    organizacaoId: 5,
    publicadoPor: 5,
    data: daquiA(18),
    horaInicio: '13:00',
    horaFim: '17:00',
    local: 'Sede da ABRAC (endereço pelo contato)',
    bairro: 'Mogi das Cruzes',
    vagasTotal: 10,
    vagasPreenchidas: 3,
    precisa: ['Separar roupas', 'Etiquetar preços', 'Cabides'],
    requisitos: 'Nenhum.',
    descricao: 'Preparação do bazar que arrecada fundos para o acolhimento.',
  },
  {
    id: 15,
    titulo: 'Vacinação de cães e gatos: apoio na fila',
    categoria: 'Animais',
    organizacaoId: 6,
    publicadoPor: 6,
    data: daquiA(25),
    horaInicio: '08:00',
    horaFim: '14:00',
    local: 'Quadra da escola estadual',
    bairro: 'Braz Cubas',
    vagasTotal: 12,
    vagasPreenchidas: 2,
    precisa: ['Organizar a fila', 'Preencher fichas', 'Coleiras e guias'],
    requisitos: 'Maiores de 16 anos.',
    descricao: 'Apoio à campanha de vacinação com veterinários parceiros.',
  },
]

export default mutiroes
